# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6e4600e1e5d85be52eaab825ac0d9b936facf50b0eb48be30112348259c455c1c0e9826da8e06b573cee2984bc496aae2bf524cfc0a8f13ef45088f634f057

test:
  secret_key_base: 7bff4a7afe0877311ef35c6f7521d52484c0a0601ee956090054811c02d69b480b290eb468b45d9f1c5c9c3c9bc38a4502d2d175e8a954121cc8ad51028e25e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
